id: P49395C96
initial_creation_type: input
source_metadata:
  title: Magnetizing Series
  language: fr
  description: 'Texts on the theme of magnetizing or bringing under one’s control
    (dbang du sdud pa):'
  volume:
    72a8ed33872542e9a6fdb241dfdfcefc:
      title: Magnetizing (Wangdü) Prayer
      parent: Prayers
    002577a6966e4e8ca1d1beb26c89af66:
      title: 'Wangdü: The Great Cloud of Blessings—The Prayer which Magnetizes All
        that Appears and Exists'
      parent: Prayers
    bda4a29540ce4712a6bcfb26e675d55f:
      title: 'Swift Enchantment of the Three Realms: A Sādhana of Red Tārā'
      parent: Sādhanas
created_at: '2022-03-01T04:30:45.115652'
last_modified_at: '2022-03-01T04:30:45.115654'
